[general]
live_config_reload = true
import = [
        "~/.config/alacritty/coolnight.toml",
        "/Users/ben/.config/alacritty/alacritty-mac.toml",
        "/home/ben/.config/alacritty/alacritty-linux.toml"
    ]

# [terminal.shell]
# program = "tmux"
