[font]
size = 10.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
opacity = 1

[scrolling]
history = 10000

[env]
XCURSOR_SIZE = "16"
